# Generated by Django 2.2.2 on 2019-06-15 07:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Phone must have the next format +38(068)111-11-11', regex='^\\+\\d{2}\\(?([0-9]{3})\\)[0-9]{3}\\-[0-9]{2}\\-[0-9]{2}$')])),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client_crud.Address')),
            ],
        ),
    ]
