# Generated by Django 2.2.2 on 2019-06-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client_crud.Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
